### ISSUE TITLE
Replacing model with point cloud ?

### ISSUE THREAD

**Issue by smartspacemonkey** [yangjiaolong/Go-ICP#1]
Hi,

Is Go-ICP algorithm able to register 2 point clouds of a scanned 3d object taken from 2 different points of view ?

Thanks.

**Comment by yangjiaolong** [comment]
Yes. The points in the non-overlapping regions should be regarded as outliers and the trimming percentage parameter should be set properly to handle them. Pls refer to our TPAMI paper for more details.

**Comment by smartspacemonkey** [comment]
thanks, but unfortunately, it didn't work, even with trimming.

I have created [point cloud files of bunny](https://ufile.io/xk5ni) in your format so you could test it yourself.
