### ISSUE TITLE
Thank you for the code

### ISSUE THREAD

**Issue by aalavandhaann** [yangjiaolong/Go-ICP#2]
Dear yangjiaolong,

Firstly, thank you for this contribution that is a real useful contribution for the geometry processing community. Secondly, I have forked your code to a different repository and converted the code base such that it works for ```python```. I have wrapped your existing ```c++``` classes using Cython and Autowrap to retain the efficiency and robustness. I thought it is better to inform you prior so that I shall be able to honor any obligations from my end. Kindly let me know if there is any problem with this direction and I shall take down my repository. 

Once again thank you for this valuable contribution.

Regards,

#0K

**Comment by yangjiaolong** [comment]
No problem @aalavandhaann and thanks for the python wrapper. I'll add a link to your repo in my readme.

**Comment by aalavandhaann** [comment]
Thank you very much.
