### ISSUE TITLE
How long does this go-icp take? Is it possible to use openmp or cuda to the ndt algorithm?

### ISSUE THREAD

**Issue by hunkyu** [yangjiaolong/Go-ICP#3]
How long does this go-icp take? Is it possible to use openmp or cuda to the ndt algorithm?

**Comment by yangjiaolong** [comment]
It depends. Pls refer to our journal paper for details regarding running time.

Both distance transform computation and our BnB algorithm can be speedup by openmp or cuda. I did not manage to do it due to time constrain. Let me know if you have implemented it.

**Comment by hunkyu** [comment]
👌

**Comment by bomtorazek** [comment]
@hunkyu 
Did you implement it, sir?
